server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# A mesma chave que está no user-service.yml
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE   # O 'lb://' significa Load Balancer acoplado ao Eureka
          predicates:
            - Path=/api/users/** # Tudo o que começar com /api/users vai para o USER-SERVICE
          filters:
            - AuthenticationFilter # Aplica o nosso filtro de segurança aqui!
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter